version: "3.9"

services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - redis  
    environment:
      - REDIS_HOST=redis 
    env_file:
      - .env  

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
