version: "3.8"

services:
  server:
    image: 134059028578.dkr.ecr.us-east-1.amazonaws.com/practice/fastapi_ci-cd_app:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs
    depends_on:
      - redis
    networks:  # Додано явне підключення до мережі
      - app-network

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    networks:  # Додано явне підключення до мережі
      - app-network

volumes:
  redis_data:

networks:  # Додано визначення мережі
  app-network:
    driver: bridge