"""Add snapshots to sessions and user_responces

Revision ID: 2e78157eb482
Revises: bda35afc035f
Create Date: 2025-04-23 17:10:31.287431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e78157eb482'
down_revision: Union[str, None] = 'bda35afc035f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('topic_title', sa.String(), nullable=False))
    op.alter_column('sessions', 'topic_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('sessions_topic_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    op.add_column('userresponses', sa.Column('question_text', sa.Text(), nullable=False))
    op.alter_column('userresponses', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('userresponses_question_id_fkey', 'userresponses', type_='foreignkey')
    op.create_foreign_key(None, 'userresponses', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userresponses', type_='foreignkey')
    op.create_foreign_key('userresponses_question_id_fkey', 'userresponses', 'questions', ['question_id'], ['id'])
    op.alter_column('userresponses', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('userresponses', 'question_text')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_topic_id_fkey', 'sessions', 'topics', ['topic_id'], ['id'])
    op.alter_column('sessions', 'topic_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sessions', 'topic_title')
    # ### end Alembic commands ###
