"""Add topic_id to sessions

Revision ID: bda35afc035f
Revises: b106cad22d00
Create Date: 2025-04-23 15:50:14.849671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda35afc035f'
down_revision: Union[str, None] = 'b106cad22d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('topic_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'topics', ['topic_id'], ['id'])
    op.drop_column('sessions', 'session_name')
    op.add_column('topics', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'description')
    op.add_column('sessions', sa.Column('session_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'topic_id')
    # ### end Alembic commands ###
