"""Added CASCADE delete for questions

Revision ID: 9219e1dbf6f0
Revises: 2e78157eb482
Create Date: 2025-04-24 18:11:23.459813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9219e1dbf6f0'
down_revision: Union[str, None] = '2e78157eb482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_topic_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_topic_id_fkey', 'questions', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###
