name: Deploy to AWS Linux EC2
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and push
        run: |
          docker build -t fastapi_ci-cd_app .  # Змінили назву тегу
          docker tag fastapi_ci-cd_app:latest ${{ secrets.ECR_REGISTRY }}:latest  # Видалили зайвий шлях
          docker push ${{ secrets.ECR_REGISTRY }}:latest

      - name: Deploy to EC2 (AWS Linux)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Оновлення та встановлення Docker
            sudo yum update -y
            sudo yum install docker -y
            sudo service docker start
            
            # Автентифікація в ECR
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            
            # Деплой
            sudo docker pull ${{ secrets.ECR_REGISTRY }}:latest
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true
            sudo docker run -d -p 8000:8000 --name fastapi-app ${{ secrets.ECR_REGISTRY }}:latest