name: Deploy to AWS Linux EC2
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and push
        run: |
          docker build -t fastapi_ci-cd_app .
          docker tag fastapi_ci-cd_app:latest ${{ secrets.ECR_REGISTRY }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}:latest

      - name: Create .env and certs for upload
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          mkdir -p certs
          echo "${{ secrets.JWT_PRIVATE_PEM }}" > certs/jwt-private.pem
          echo "${{ secrets.JWT_PUBLIC_PEM }}" > certs/jwt-public.pem

      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env,certs/jwt-private.pem,certs/jwt-public.pem,docker-compose.yml" 
          target: "~/app"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
            echo "=== Перелік файлів у ~/app ==="
            ls -la ~/app/
            echo "=== Вміст docker-compose.yml ==="
            cat ~/app/docker-compose.yml
            
            aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            
            cd ~/app
            sudo /usr/local/bin/docker-compose down || true
            sudo /usr/local/bin/docker-compose pull
            sudo /usr/local/bin/docker-compose up -d
            
            echo "=== Стан контейнерів ==="
            sudo docker ps
            echo "=== Логи docker-compose ==="
            sudo /usr/local/bin/docker-compose logs